name: Cache

on:
  push:
    branches:
      - "main"

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
  MINT_LINK_PATH: .mint/bin
  MINT_PATH: .mint/lib

jobs:
  cache-dependencies:
    name: Cache dependencies
    runs-on: macos-14
    steps:
      - name: Check out repo
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Configure Ruby
        uses: ruby/setup-ruby@c04af2bb7258bb6a03df1d3c1865998ac9390972 # v1.194.0
        with:
          bundler-cache: true

      - name: Cache Mint packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Cache SPM packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Install Mint
        run: |
          brew install mint
          ./Scripts/bootstrap.sh
