name: Cache

on:
  push:
    branches:
      - "main"

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
  MINT_LINK_PATH: .mint/bin
  MINT_PATH: .mint/lib

jobs:
  cache-dependencies:
    name: Cache dependencies
    runs-on: macos-14
    steps:
      - name: Check out repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Configure Ruby
        uses: ruby/setup-ruby@f321cf5a4d1533575411f8752cf25b86478b0442 # v1.193.0
        with:
          bundler-cache: true

      - name: Cache Mint packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Cache SPM packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: build/DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Install Mint
        run: |
          brew install mint
          ./Scripts/bootstrap.sh
